config/routes.rb
Rails.application.routes.draw do

  root to: 'beers#index'

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    confirmations: "admins/confirmations",
    passwords:     "admins/passwords",
    sessions:      "admins/sessions",
    unlocks:       "admins/unlocks"
  }

  resources :beers do
    member do
      get :purchase
    end
  end
end

app/models/beer.rb
class Beer < ApplicationRecord

  scope :not_deleted, -> { where(deleted_at: nil) }
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show, :purchase]

  expose(:beers) { Beer.not_deleted }
  expose(:beer, scope: :not_deleted)
  expose(:all_beers) { Beer.all }

  def index
    respond_to do |format|
      format.html
      format.json { render json: BeersDatatable.new(view_context) }
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if beer.save
        format.html { redirect_to beer, notice: 'Beer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if beer.update(beer_params)
        format.html { redirect_to beer, notice: 'Beer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def purchase
    respond_to do |format|
      if beer.update_attributes(deleted_at: Time.now)
        format.js
      else
        format.js
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :style, :brewer, :store, :desc, :deleted_at)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<div class='beer-form-wrapper'>
  <%= simple_form_for(beer) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :brewer %>
      <%= f.input :style %>
      <%= f.input :store %>
      <%= f.input :link %>
      <%= f.input :desc %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-outline-success' %>
    </div>
  <% end %>
</div>

app/views/beers/edit.html.erb
<p id="notice"><%= notice %></p>

<h1 class='beer-header'>
  <i class="fa fa-beer beer-icon text-warning"></i>Edit <%= beer.name.titleize %>
  <%= link_to 'Back', beers_path, class: 'btn btn-primary btn-sm', style: 'float: right; margin-top: 7px;' %>
</h1>

<%= render 'form', beer: beer %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='beer-header' style='border-bottom: 0;'>
  <i class="fa fa-beer beer-icon text-warning"></i>Dustin's Beer Requests
  <% if current_admin %>
    <%= link_to 'New Beer', new_beer_path, class: 'btn btn-outline-success btn-sm', style: 'float: right; margin-top: 7px;' %>
  <% end %>
</h1>

<table class='sortable table table-striped table-rounded'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brewer</th>
      <th>Style</th>
      <th>Store</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% beers.each do |beer| %>
      <tr id='beer-<%= beer.id %>'>
        <td><%= beer.name.titleize %></td>
        <td><%= beer.brewer.titleize %></td>
        <td><%= beer.style.titleize %></td>
        <td><%= beer.store.titleize %></td>
        <td><%= link_to 'Link', beer.link, target: '_blank', class: 'beer-url' if beer.link.present? %></td>
        <td><%= link_to 'Details', beer, class: 'btn btn-outline-info btn-sm'  %></td>
        <% if current_admin %>
          <td><%= link_to 'Edit', edit_beer_path(beer), class: 'btn btn-outline-primary btn-sm'  %></td>
        <% end %>
        <td><%= link_to 'Purchase', purchase_beer_path(beer), data: { confirm: 'Are you buying a beer for Dustin?' }, remote: true, class: 'btn btn-success btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/beers/new.html.erb
<p id="notice"><%= notice %></p>

<h1 class='beer-header'>
  <i class="fa fa-beer beer-icon text-warning"></i>New Beer
  <%= link_to 'Back', beers_path, class: 'btn btn-primary btn-sm', style: 'float: right; margin-top: 7px;' %>
</h1>

<%= render 'form', beer: beer %>

app/views/beers/purchase.js.erb
$('#beer-<%= beer.id %>').remove()

flashAlert('We just sent Dustin an email letting him know you purchased him a beer!', 'success', 10000)

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class='beer-header'>
  <i class="fa fa-beer beer-icon text-warning"></i><%= beer.name.titleize %>
  <%= link_to 'Back', beers_path, class: 'btn btn-primary btn-sm', style: 'float: right; margin-top: 7px;' %>
  <% if current_admin %>
    <%= link_to 'Edit', edit_beer_path(beer), class: 'btn btn-outline-success btn-sm', style: 'float: right; margin-top: 7px; margin-right: 10px;' %>
  <% end %>
</h1>

<div class='beer-info-wrapper'>
  <table>
    <tr>
      <td class='beer-label'>Name:</td>
      <td class='beer-data'><%= beer.name.titleize %></td>
    </tr>

    <tr>
      <td class='beer-label'>Brewer:</td>
      <td class='beer-data'><%= beer.brewer.titleize %></td>
    </tr>

    <tr>
      <td class='beer-label'>Style:</td>
      <td class='beer-data'><%= beer.style.titleize %></td>
    </tr>

    <tr>
      <td class='beer-label'>Store:</td>
      <td class='beer-data'><%= beer.store.titleize %></td>
    </tr>

    <tr>
      <td class='beer-label'>URL:</td>
      <td class='beer-data'><%= link_to 'Link', beer.link, target: '_blank', class: 'beer-url' if beer.link.present? %></td>
    </tr>

    <tr>
      <td class='beer-label'>Description:</td>
      <td class='beer-data'><%= beer.desc %></td>
    </tr>
  </table>
</div>